version: "3.7"

services:
    db_postgres:
        image: postgres
        container_name: db_postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/data/postgres

    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    # app:
    #     build: . # build the app image
    #     container_name: rentx
    #     ports:
    #         - 3333:3333
    #     volumes:
    #         - .:/usr/app
    #     links:
    #         - db_postgres
    #     depends_on:
    #         - db_postgres

volumes:
    pgdata:
        driver: local
